import React from 'react'
  function washingmachine() {
		return(
	<div>
	<h1>Differnet types of washing machine.</h1>
 <p>There are several different types of washing machines available in the market. Some of the common types of washing machines are:Top-Load Washing Machine: This is the most traditional and commonly used type of washing machine. In a top-load washing machine, clothes are loaded from the top, and the machine uses an agitator or impeller to wash the clothes. Top-load washing machines are generally more affordable and have a shorter wash cycle.
        Front-Load Washing Machine: In a front-load washing machine, clothes are loaded from the front, and the machine uses a drum to wash the clothes by rotating them. Front-load washing machines are known for their efficiency in water and energy consumption and are generally more gentle on clothes. They are also stackable, which can save space in smaller laundry rooms.
        High-Efficiency (HE) Washing Machine: High-efficiency washing machines are designed to use less water and energy compared to traditional top-load washing machines. They typically have larger capacities and faster spin speeds to extract more water from clothes, resulting in shorter drying times.
        Compact Washing Machine: Compact washing machines are smaller in size and are designed for apartments, small homes, or for those who have limited space for a laundry area. They are available in both top-load and front-load configurations and usually have smaller capacities compared to standard-sized washing machines.
        Top-Load Agitator Washing Machine: This type of washing machine uses an agitator in the center of the drum to wash clothes. Agitators are fins or paddles that move the clothes around in the water to clean them. Top-load agitator washing machines are known for their strong cleaning performance but may be harsher on clothes compared to other types of washing machines.
        Top-Load Impeller Washing Machine: This type of washing machine uses an impeller, which is a low-profile disc located at the bottom of the drum, to wash clothes. The impeller creates a swirling motion in the water to clean the clothes. Top-load impeller washing machines are known for their gentle cleaning performance and larger capacity. 
        Washer-Dryer Combo: A washer-dryer combo is a single unit that combines both washing and drying functions in one machine. They are suitable for those who have limited space and want the convenience of a washer and dryer in a single unit.
        These are some of the different types of washing machines available in the market. When choosing a washing machine, consider factors such as your laundry needs, space availability, budget, and energy efficiency to make the best decision for your home.</p>